### ISSUE TITLE
Convert Static website to Dynamic in React? Anyone up for challenge?

### ISSUE THREAD

**Issue by fineanmol** [fineanmol/Hacktoberfest2022#1577]
This is a static website where we have alots of constraints. Can anyone take the challenge to convert this into a dynamic REACT JS application?

**Comment by prajwalkulkarni** [comment]
Hello @fineanmol, I'd like to take this up and update the site to be a react application.

**Comment by prajwalkulkarni** [comment]
I'd need some heads-up with what elements of the site are going to be dynamic. Is it just how the components are rendered or anything more to it? Should a database be used to store the contributors, and how do you plan to add the contributors, is it going to be added by the contributors themselves? Should there be a CI pipeline added to generate a build each time a PR is merged? Any additional info is also appreciated.

**Comment by fineanmol** [comment]
> Sure @prajwalkulkarni 

Mainly a way to make Contribution.html file content dynamic, The main problem we are trying to solve is that users list is getting increased after every PR merged. So now contributors have to scroll too much to enter their details. 
If we can make a way to ease that process. 
Contributors can add their information in some Json or text file from which we can get the list of users and render it on our component. And Yes we have to make a github CI/CD pipeline to generate a build everytime a PR is merged. (otherwise the changes won't even reflect on live) 
It'll help us to merge More PR and less PR conflicts.

**Comment by prajwalkulkarni** [comment]
Okay, the main issue to address here is the growing contributor's list which is increasing along with the incessant growth in the codebase of `contribution.html`, to solve this, the list should be placed out of the script and the main script should be modularised, I've raised an issue to address this #1591 (kindly assign it to me so that I can add PR reflecting those changes). Once this is done, I think it is possible to write a workflow to add contributors automatically to the list and build the page on every PR merged(instead of users adding their information manually). Once this code is refactored, converting the site to be programmed declaratively should be fairly simple. Let me know what do you think of this.

**Comment by fineanmol** [comment]
> 

Go Ahead with the changes

**Comment by ImArnoldDCODES** [comment]
Hello @fineanmol I will love to take part in this and update this to a react web application

**Comment by prajwalkulkarni** [comment]
Hello @fineanmol, I've created a PR #1806 that separates the contributor's list from the main script tag. So until the workflow is ready, people can add their details in `contributors/data.js` and when the workflow is ready, it shall automatically add to it and build the site on every merged PR. Could you kindly review and merge the PR so that I can start working on the automation workflow?
